import { ACCESS_LEVELS } from './personas';
import { ENTITY_NAMES } from './constants';

/**
 * All possible actions in the permission system.
 */
export const ACTIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  APPROVE: 'approve',
  WAIVE: 'waive',
  EXPORT: 'export',
  CONFIGURE: 'configure',
  EXECUTE: 'execute',
  ADMINISTER: 'administer',
};

/**
 * All entity type keys used in the permission matrix.
 */
export const ENTITY_TYPES = {
  PORTFOLIO: 'PORTFOLIO',
  APPLICATION: 'APPLICATION',
  RELATIONSHIP: 'RELATIONSHIP',
  TECH_CATEGORY: 'TECH_CATEGORY',
  TECH_STANDARD: 'TECH_STANDARD',
  TECH_ENTRY: 'TECH_ENTRY',
  DEFINITION: 'DEFINITION',
  ENVIRONMENT: 'ENVIRONMENT',
  TECH_DEBT: 'TECH_DEBT',
  QUALITY_GATE: 'QUALITY_GATE',
  GOVERNANCE_RECORD: 'GOVERNANCE_RECORD',
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
  WAIVER: 'WAIVER',
  EVIDENCE: 'EVIDENCE',
  USER: 'USER',
  ROLE: 'ROLE',
  INTEGRATION: 'INTEGRATION',
  NOTIFICATION: 'NOTIFICATION',
  AI_ANALYSIS: 'AI_ANALYSIS',
  PDE_CONFIG: 'PDE_CONFIG',
  DEMO_SCENARIO: 'DEMO_SCENARIO',
  SCHEDULE: 'SCHEDULE',
  AUDIT_LOG: 'AUDIT_LOG',
  USE_CASE: 'USE_CASE',
};

const ALL_ACTIONS = Object.values(ACTIONS);

const VIEW_ONLY = [ACTIONS.VIEW];
const VIEW_EXPORT = [ACTIONS.VIEW, ACTIONS.EXPORT];
const VIEW_CREATE_EDIT = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT];
const VIEW_CREATE_EDIT_EXPORT = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.EXPORT];
const VIEW_CREATE_EDIT_DELETE = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.DELETE];
const VIEW_CREATE_EDIT_DELETE_EXPORT = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.DELETE, ACTIONS.EXPORT];
const FULL_CRUD_EXPORT = [ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.DELETE, ACTIONS.EXPORT];

/**
 * Helper to build a permission set from an array of allowed actions.
 * @param {string[]} allowedActions
 * @returns {Object<string, boolean>}
 */
const buildPermissions = (allowedActions) => {
  const perms = {};
  ALL_ACTIONS.forEach((action) => {
    perms[action] = allowedActions.includes(action);
  });
  return perms;
};

const NONE = buildPermissions([]);
const VIEW_PERMS = buildPermissions(VIEW_ONLY);
const VIEW_EXPORT_PERMS = buildPermissions(VIEW_EXPORT);
const VIEW_CREATE_EDIT_PERMS = buildPermissions(VIEW_CREATE_EDIT);
const VIEW_CREATE_EDIT_EXPORT_PERMS = buildPermissions(VIEW_CREATE_EDIT_EXPORT);
const VIEW_CREATE_EDIT_DELETE_PERMS = buildPermissions(VIEW_CREATE_EDIT_DELETE);
const FULL_CRUD_EXPORT_PERMS = buildPermissions(FULL_CRUD_EXPORT);
const ALL_PERMS = buildPermissions(ALL_ACTIONS);

/**
 * Complete permission matrix mapping accessLevel × entityType → action permissions.
 *
 * Structure: PERMISSION_MATRIX[accessLevel][entityType] = { view: bool, create: bool, ... }
 *
 * @type {Object<string, Object<string, Object<string, boolean>>>}
 */
export const PERMISSION_MATRIX = {
  [ACCESS_LEVELS.ADMIN]: {
    [ENTITY_TYPES.PORTFOLIO]: ALL_PERMS,
    [ENTITY_TYPES.APPLICATION]: ALL_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: ALL_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: ALL_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: ALL_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: ALL_PERMS,
    [ENTITY_TYPES.DEFINITION]: ALL_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: ALL_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: ALL_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: ALL_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: ALL_PERMS,
    [ENTITY_TYPES.APPROVAL_REQUEST]: ALL_PERMS,
    [ENTITY_TYPES.WAIVER]: ALL_PERMS,
    [ENTITY_TYPES.EVIDENCE]: ALL_PERMS,
    [ENTITY_TYPES.USER]: ALL_PERMS,
    [ENTITY_TYPES.ROLE]: ALL_PERMS,
    [ENTITY_TYPES.INTEGRATION]: ALL_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: ALL_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: ALL_PERMS,
    [ENTITY_TYPES.PDE_CONFIG]: ALL_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: ALL_PERMS,
    [ENTITY_TYPES.SCHEDULE]: ALL_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: ALL_PERMS,
    [ENTITY_TYPES.USE_CASE]: ALL_PERMS,
  },

  [ACCESS_LEVELS.EXECUTIVE]: {
    [ENTITY_TYPES.PORTFOLIO]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.APPLICATION]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.APPROVAL_REQUEST]: buildPermissions([ACTIONS.VIEW, ACTIONS.APPROVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.WAIVER]: buildPermissions([ACTIONS.VIEW, ACTIONS.APPROVE, ACTIONS.WAIVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.EVIDENCE]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXPORT, ACTIONS.EXECUTE]),
    [ENTITY_TYPES.PDE_CONFIG]: VIEW_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_EXPORT_PERMS,
  },

  [ACCESS_LEVELS.STRATEGIC]: {
    [ENTITY_TYPES.PORTFOLIO]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.APPLICATION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.EXPORT, ACTIONS.APPROVE]),
    [ENTITY_TYPES.APPROVAL_REQUEST]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.APPROVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.WAIVER]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.APPROVE, ACTIONS.WAIVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.EVIDENCE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXECUTE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.PDE_CONFIG]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
  },

  [ACCESS_LEVELS.MANAGEMENT]: {
    [ENTITY_TYPES.PORTFOLIO]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.APPLICATION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.APPROVAL_REQUEST]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.APPROVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.WAIVER]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.WAIVE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.EVIDENCE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: buildPermissions([ACTIONS.VIEW, ACTIONS.EXECUTE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.PDE_CONFIG]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
  },

  [ACCESS_LEVELS.OPERATIONAL]: {
    [ENTITY_TYPES.PORTFOLIO]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.APPLICATION]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.APPROVAL_REQUEST]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE, ACTIONS.EXPORT]),
    [ENTITY_TYPES.WAIVER]: VIEW_EXPORT_PERMS,
    [ENTITY_TYPES.EVIDENCE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: VIEW_PERMS,
    [ENTITY_TYPES.PDE_CONFIG]: VIEW_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_CREATE_EDIT_EXPORT_PERMS,
  },

  [ACCESS_LEVELS.CONTRIBUTOR]: {
    [ENTITY_TYPES.PORTFOLIO]: VIEW_PERMS,
    [ENTITY_TYPES.APPLICATION]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: VIEW_PERMS,
    [ENTITY_TYPES.APPROVAL_REQUEST]: buildPermissions([ACTIONS.VIEW, ACTIONS.CREATE]),
    [ENTITY_TYPES.WAIVER]: VIEW_PERMS,
    [ENTITY_TYPES.EVIDENCE]: VIEW_CREATE_EDIT_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: VIEW_PERMS,
    [ENTITY_TYPES.PDE_CONFIG]: VIEW_PERMS,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_CREATE_EDIT_PERMS,
  },

  [ACCESS_LEVELS.READ_ONLY]: {
    [ENTITY_TYPES.PORTFOLIO]: VIEW_PERMS,
    [ENTITY_TYPES.APPLICATION]: VIEW_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_DEBT]: VIEW_PERMS,
    [ENTITY_TYPES.QUALITY_GATE]: VIEW_PERMS,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: VIEW_PERMS,
    [ENTITY_TYPES.APPROVAL_REQUEST]: VIEW_PERMS,
    [ENTITY_TYPES.WAIVER]: VIEW_PERMS,
    [ENTITY_TYPES.EVIDENCE]: VIEW_PERMS,
    [ENTITY_TYPES.USER]: VIEW_PERMS,
    [ENTITY_TYPES.ROLE]: VIEW_PERMS,
    [ENTITY_TYPES.INTEGRATION]: VIEW_PERMS,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: VIEW_PERMS,
    [ENTITY_TYPES.PDE_CONFIG]: NONE,
    [ENTITY_TYPES.DEMO_SCENARIO]: VIEW_PERMS,
    [ENTITY_TYPES.SCHEDULE]: VIEW_PERMS,
    [ENTITY_TYPES.AUDIT_LOG]: VIEW_PERMS,
    [ENTITY_TYPES.USE_CASE]: VIEW_PERMS,
  },

  [ACCESS_LEVELS.EXTERNAL]: {
    [ENTITY_TYPES.PORTFOLIO]: NONE,
    [ENTITY_TYPES.APPLICATION]: VIEW_PERMS,
    [ENTITY_TYPES.RELATIONSHIP]: NONE,
    [ENTITY_TYPES.TECH_CATEGORY]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_STANDARD]: VIEW_PERMS,
    [ENTITY_TYPES.TECH_ENTRY]: VIEW_PERMS,
    [ENTITY_TYPES.DEFINITION]: VIEW_PERMS,
    [ENTITY_TYPES.ENVIRONMENT]: NONE,
    [ENTITY_TYPES.TECH_DEBT]: NONE,
    [ENTITY_TYPES.QUALITY_GATE]: NONE,
    [ENTITY_TYPES.GOVERNANCE_RECORD]: NONE,
    [ENTITY_TYPES.APPROVAL_REQUEST]: NONE,
    [ENTITY_TYPES.WAIVER]: NONE,
    [ENTITY_TYPES.EVIDENCE]: NONE,
    [ENTITY_TYPES.USER]: NONE,
    [ENTITY_TYPES.ROLE]: NONE,
    [ENTITY_TYPES.INTEGRATION]: NONE,
    [ENTITY_TYPES.NOTIFICATION]: VIEW_PERMS,
    [ENTITY_TYPES.AI_ANALYSIS]: NONE,
    [ENTITY_TYPES.PDE_CONFIG]: NONE,
    [ENTITY_TYPES.DEMO_SCENARIO]: NONE,
    [ENTITY_TYPES.SCHEDULE]: NONE,
    [ENTITY_TYPES.AUDIT_LOG]: NONE,
    [ENTITY_TYPES.USE_CASE]: NONE,
  },
};

/**
 * Checks whether a given access level has permission to perform an action on an entity type.
 * @param {string} accessLevel - One of ACCESS_LEVELS values (e.g., 'admin', 'executive').
 * @param {string} entityType - One of ENTITY_TYPES keys (e.g., 'PORTFOLIO', 'APPLICATION').
 * @param {string} action - One of ACTIONS values (e.g., 'view', 'create', 'edit').
 * @returns {boolean} True if the action is permitted, false otherwise.
 */
export const checkPermission = (accessLevel, entityType, action) => {
  if (
    typeof accessLevel !== 'string' ||
    typeof entityType !== 'string' ||
    typeof action !== 'string'
  ) {
    return false;
  }

  const levelPerms = PERMISSION_MATRIX[accessLevel];
  if (!levelPerms) {
    return false;
  }

  const entityPerms = levelPerms[entityType];
  if (!entityPerms) {
    return false;
  }

  return entityPerms[action] === true;
};

/**
 * Returns all allowed actions for a given access level and entity type.
 * @param {string} accessLevel - One of ACCESS_LEVELS values.
 * @param {string} entityType - One of ENTITY_TYPES keys.
 * @returns {string[]} Array of allowed action strings.
 */
export const getAllowedActions = (accessLevel, entityType) => {
  if (typeof accessLevel !== 'string' || typeof entityType !== 'string') {
    return [];
  }

  const levelPerms = PERMISSION_MATRIX[accessLevel];
  if (!levelPerms) {
    return [];
  }

  const entityPerms = levelPerms[entityType];
  if (!entityPerms) {
    return [];
  }

  return ALL_ACTIONS.filter((action) => entityPerms[action] === true);
};

/**
 * Returns all entity types that a given access level can perform a specific action on.
 * @param {string} accessLevel - One of ACCESS_LEVELS values.
 * @param {string} action - One of ACTIONS values.
 * @returns {string[]} Array of entity type keys.
 */
export const getEntitiesForAction = (accessLevel, action) => {
  if (typeof accessLevel !== 'string' || typeof action !== 'string') {
    return [];
  }

  const levelPerms = PERMISSION_MATRIX[accessLevel];
  if (!levelPerms) {
    return [];
  }

  return Object.keys(levelPerms).filter(
    (entityType) => levelPerms[entityType][action] === true
  );
};

/**
 * Checks whether a given access level has any write permissions (create, edit, delete) on any entity.
 * @param {string} accessLevel - One of ACCESS_LEVELS values.
 * @returns {boolean}
 */
export const hasAnyWritePermission = (accessLevel) => {
  if (typeof accessLevel !== 'string') {
    return false;
  }

  const levelPerms = PERMISSION_MATRIX[accessLevel];
  if (!levelPerms) {
    return false;
  }

  const writeActions = [ACTIONS.CREATE, ACTIONS.EDIT, ACTIONS.DELETE];

  return Object.values(levelPerms).some((entityPerms) =>
    writeActions.some((action) => entityPerms[action] === true)
  );
};